In [121]:
from bs4 import BeautifulSoup
import requests

all_hyperlinks = []

for page_num in range(1, 3):  #this way it goes thru both pages without having two diff links
    url = f"https://www.lse.ac.uk/student-life/accommodation/search-accommodation?collection=lse-accommodation&pageIndex={page_num}&sort=metaavailability"
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        accommodation_titles = soup.find_all('h2', class_='card__title')
        hyperlinks = []
        for title in accommodation_titles:
            hyperlink = title.find('a')['href']
            hyperlinks.append(hyperlink)
        all_hyperlinks.extend(hyperlinks)

    except Exception as e:
        print("An error occurred:", e)

print(all_hyperlinks)

['http://www.lse.ac.uk/student-life/accommodation/halls/college-hall/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/international-hall/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/butlers-wharf-residence/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/bankside-house/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/carr-saunders-hall/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/connaught-hall/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/high-holborn-residence/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/urbanest-westminster-bridge/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/lilian-knowles-house/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/passfield-hall/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/nutford-house/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/rosebery-hall/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/the-garden-halls/home.aspx', 'http://www.lse.ac.uk/student-life/accommodation/halls/sidney-webb-house/home.aspx']

In [127]:
from bs4 import BeautifulSoup
import requests
import pandas as pd

accommodation_info = []
url = 'http://www.lse.ac.uk/student-life/accommodation/halls/rosebery-hall/home.aspx'
response = requests.get(url)
response.raise_for_status()  
soup = BeautifulSoup(response.text, 'html.parser')
room_type = soup.find_all('h2', class_='roomlist_title')
bathroom = soup.find_all('p', class_="roomlist_position")
print(len(room_type), "room types found")  # Debugging output
print(len(bathrooms), "bathrooms found")  # Debugging output
for room in room_type:
    print(room.text)

0 room types found
0 bathrooms found

In [124]:
import requests
from bs4 import BeautifulSoup

rooms_info = []

all_hyperlinks = ['http://www.lse.ac.uk/student-life/accommodation/halls/rosebery-hall/home.aspx']

for hyperlink in all_hyperlinks:
    
    response = requests.get(hyperlink)
    response.raise_for_status()  
    soup = BeautifulSoup(response.text, 'html.parser')

    # Find the room type and bathroom information
    # Using find() since find_all() returns a list and we need a single item
    room_type = soup.find_all('h2', class_='roomlist_title')
    bathroom = soup.find_all('p', class_='roomlist_position')
  

    # Append the data as a dictionary to the rooms_info list
    rooms_info.append({
        'hyperlink': hyperlink,
        'room_type': room_type.text.strip(),
        'bathroom': bathroom.text.strip(),
    })

# Printing each room's information
for info in rooms_info:  # Fixed typo in variable name
    print("Hyperlink:", info['hyperlink'])
    print("Room Type:", info['room_type'])
    print("Bathroom:", info['bathroom'])
    print()  # This ensures a blank line between entries for better readability

AttributeError: ResultSet object has no attribute 'text'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [86]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

all_hyperlinks = ['http://www.lse.ac.uk/student-life/accommodation/halls/international-hall/home.aspx',]

all_data = []  

for url in all_hyperlinks:
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        
        
        accommodation_title_element = soup.find('h1', class_='heroBanner__title')
        accommodation_title = accommodation_title_element.get_text(strip=True) if accommodation_title_element else "Title Not Found"

        h2_tags = []  
        p_tags = []   


        rooms_divs = soup.find_all('div', class_='rooms')
        for div in rooms_divs:
            h2_tags.extend([h2.get_text(strip=True) for h2 in div.find_all('h2')])
            p_tags.extend([p.get_text(strip=True) for p in div.find_all('p')])

        shared_rooms = []
        private_room = []

        for item in p_tags:
            if item in ["Shared bathroom", "Private bathroom"] and private_room:
                shared_rooms.append(private_room)
                private_room = [item]
            else:
                private_room.append(item)

        if private_room:
            shared_rooms.append(private_room)

        for room in shared_rooms:
            if len(room) >= 8:
                contract_info = room[5]
                cost_match = re.search(r"Contract cost:\s*£([\d,\.]+)", contract_info)
                length_match = re.search(r"Contract length:\s*(\d+)\s*weeks", contract_info)

                contract_cost = cost_match.group(1) if cost_match else "Not available"
                contract_length = length_match.group(1) + " weeks" if length_match else "Not available"

                room_dict = {
                    "Accommodation Title": accommodation_title, 
                    "Room Types": h2_tags[0] if h2_tags else "Not specified",
                    "Bathroom Type": room[0],
                    "Contract Length": contract_length,
                    "Price per Week": room[2],
                    "Availability": room[4],
                    "Contract Cost": contract_cost,
                    "Size and Details": room[6]
                }
                all_data.append(room_dict)

    except Exception as e:
        print(f"An error occurred while scraping {url}: {e}")


df_all_rooms = pd.DataFrame(all_data)

df_all_rooms

Empty DataFrame
Columns: []
Index: []

In [80]:
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re



all_data = []  # List to store data from all URLs

for url in all_hyperlinks:
    try:
        response = requests.get(url)
        response.raise_for_status()
        soup = BeautifulSoup(response.text, 'html.parser')
        
       
        accommodation_title_element = soup.find('h1', class_='heroBanner__title')
        accommodation_title = accommodation_title_element.get_text(strip=True) if accommodation_title_element else "Title Not Found"

        h2_tags = []  
        p_tags = []  
       
        rooms_divs = soup.find_all('div', class_='rooms')
        for div in rooms_divs:
            h2_tags.extend([h2.get_text(strip=True) for h2 in div.find_all('h2')])
            p_tags.extend([p.get_text(strip=True) for p in div.find_all('p')])

        shared_rooms = []
        private_room = []

        for item in p_tags:
            if item in ["Shared bathroom", "Private bathroom"] and private_room:
                shared_rooms.append(private_room)
                private_room = [item]
            else:
                private_room.append(item)

        if private_room:
            shared_rooms.append(private_room)

        for room in shared_rooms:
            if len(room) >= 8:
                contract_info = room[5]
                cost_match = re.search(r"Contract cost:\s*£([\d,\.]+)", contract_info)
                length_match = re.search(r"Contract length:\s*(\d+)\s*weeks", contract_info)

                contract_cost = cost_match.group(1) if cost_match else "Not available"
                contract_length = length_match.group(1) + " weeks" if length_match else "Not available"

                room_dict = {
                    "Accommodation Title": accommodation_title,  
                    "Room Types": h2_tags[0] if h2_tags else "Not specified",
                    "Bathroom Type": room[0],
                    "Contract Length": contract_length,
                    "Price per Week": room[2],
                    "Availability": room[4],
                    "Contract Cost": contract_cost,
                    "Size and Details": room[6]
                }
                all_data.append(room_dict)

    except Exception as e:
        print(f"An error occurred while scraping {url}: {e}")


df_all_rooms = pd.DataFrame(all_data)

df_all_rooms

,Accommodation Title,Room Types,Bathroom Type,Contract Length,Price per Week,Availability,Contract Cost,Size and Details
0,urbanest Westminster Bridge,Single room,Shared bathroom,Not available,£285.23\n\n-£310.76p/wk,No Availability,Not available,Size approx: 8.5m²
1,urbanest Westminster Bridge,Single room,Private bathroom,Not available,£286.90\n\n-£346.90p/wk,No Availability,Not available,Size approx: 13.4m²
2,urbanest Westminster Bridge,Single room,Private bathroom,Not available,£227.09\n\n-£240.22p/wk,No Availability,Not available,Size approx: 25.3m²
3,Connaught Hall,Single room,Shared bathroom,40 weeks,£273.63p/wk,No Availability,"10,906.11","Room contains single bed, wash basin, wardrobe..."
4,High Holborn Residence,Single room,Private bathroom,Not available,£333.20p/wk,No Availability,Not available,"Contract cost: £12,947.20Contract length: 39 w..."
5,Passfield Hall,Single room,Private bathroom,Not available,£287.35p/wk,No Availability,Not available,"Contract cost: £8,743.65Contract length: 31 we..."
6,Rosebery Hall,Single room,Shared bathroom,Not available,£247.80\n\n-£263.90p/wk,No Availability,Not available,Contract lenght: 39 weeksSize approx: 10.5m² t...
7,Rosebery Hall,Single room,Shared bathroom,Not available,£168.70p/wk,No Availability,"6,555.20",Size approx: 15.5m² to 17.5m²
8,Rosebery Hall,Single room,Private bathroom,39 weeks,£185.50p/wk,Limited Availability,"7,208.00",Size approx: 17.5m²
9,Sidney Webb House,Single en suite room,Private bathroom,40 weeks,£221.90\n\n-£244.65p/wk,No Availability,"8,844.30","Room with queen-size bed, wardrobe, desk and c..."
10,Sidney Webb House,Single en suite room,Private bathroom,Not available,£331.45p/wk,No Availability,"13,210.65",Contract length: 40 weeks

In [65]:
import pandas as pd

shared_rooms = []
private_room = []

for item in p_tags:
    if item in ["Shared bathroom", "Private bathroom"] and private_room:
        
        shared_rooms.append(private_room)
        private_room = [item]
    else:
        private_room.append(item)


if private_room:
    shared_rooms.append(private_room)


data = []
for room in shared_rooms:
    
    if len(room) >= 8:  
        room_dict = {
            "Bathroom Type": room[0],
            "Contract Length": room[1],
            "Price per Week": room[2],
            "Availability": room[4],
            "Contract Cost": room[5],
            "Size and Details": room[6]
        }
        data.append(room_dict)

# Create DataFrame
df_rooms = pd.DataFrame(data)

df_rooms

,Bathroom Type,Contract Length,Price per Week,Availability,Contract Cost,Size and Details
0,Shared bathroom,39-week contract,£247.80\n\n-£263.90p/wk,No Availability,"Contract cost:Rosebery Wing: £9,996.00Myddelto...",Contract lenght: 39 weeksSize approx: 10.5m² t...
1,Shared bathroom,39-week contract,£168.70p/wk,No Availability,"Contract cost: £6,555.20Contract lenght: 39 weeks",Size approx: 15.5m² to 17.5m²
2,Private bathroom,39-week contract,£185.50p/wk,Limited Availability,"Contract cost: £7,208.00Contract length: 39 weeks",Size approx: 17.5m²

In [67]:
import pandas as pd
import re 

shared_rooms = []
private_room = []


for item in p_tags:
    if item in ["Shared bathroom", "Private bathroom"] and private_room:
       
        shared_rooms.append(private_room)
        private_room = [item]
    else:
        private_room.append(item)

if private_room:
    shared_rooms.append(private_room)


data = []
for room in shared_rooms:
    if len(room) >= 8:  
        contract_info = room[5]
        cost_match = re.search(r"Contract cost:\s*£([\d,\.]+)", contract_info)
        length_match = re.search(r"Contract length:\s*(\d+)\s*weeks", contract_info)

       
        contract_cost = cost_match.group(1) if cost_match else "Not available"
        contract_length = length_match.group(1) + " weeks" if length_match else "Not available"

        room_dict = {
            "Bathroom Type": room[0],
            "Contract Length": room[1],
            "Price per Week": room[2],
            "Availability": room[4],
            "Contract Cost": contract_cost,
            "Size and Details": room[6]
        }
        data.append(room_dict)

# Create DataFrame
df_rooms = pd.DataFrame(data)

df_rooms

,Bathroom Type,Contract Length,Price per Week,Availability,Contract Cost,Size and Details
0,Shared bathroom,39-week contract,£247.80\n\n-£263.90p/wk,No Availability,Not available,Contract lenght: 39 weeksSize approx: 10.5m² t...
1,Shared bathroom,39-week contract,£168.70p/wk,No Availability,"6,555.20",Size approx: 15.5m² to 17.5m²
2,Private bathroom,39-week contract,£185.50p/wk,Limited Availability,"7,208.00",Size approx: 17.5m²

In [66]:
df_rooms.insert(0, 'Room Types', df['Room Types'])

df_rooms

,Room Types,Bathroom Type,Contract Length,Price per Week,Availability,Contract Cost,Size and Details
0,Single room,Shared bathroom,39-week contract,£247.80\n\n-£263.90p/wk,No Availability,"Contract cost:Rosebery Wing: £9,996.00Myddelto...",Contract lenght: 39 weeksSize approx: 10.5m² t...
1,Twin room,Shared bathroom,39-week contract,£168.70p/wk,No Availability,"Contract cost: £6,555.20Contract lenght: 39 weeks",Size approx: 15.5m² to 17.5m²
2,Twin en suite room,Private bathroom,39-week contract,£185.50p/wk,Limited Availability,"Contract cost: £7,208.00Contract length: 39 weeks",Size approx: 17.5m²

In [24]:
from bs4 import BeautifulSoup
import requests


url = "https://www.lse.ac.uk/student-life/accommodation/halls/rosebery-hall"

try:
    response = requests.get(url)
    response.raise_for_status()  
    soup = BeautifulSoup(response.text, 'html.parser')
    
    rooms_content = []  
    
   
    rooms_divs = soup.find_all('div', class_='rooms')
    for div in rooms_divs:
        content = {"h2": "", "p": ""}    
        content["h2"] = " ".join(h2.get_text(strip=True) for h2 in div.find_all('h2'))
        content["p"] = " ".join(p.get_text(strip=True) for p in div.find_all('p'))
        rooms_content.append(content)

except Exception as e:
    print("An error occurred:", e)


for room in rooms_content:
    if room["h2"]: 
        print("H2:", room["h2"])
    if room["p"]:  
        print("P:", room["p"])

H2: Single room Twin room Twin en suite room
P: Shared bathroom 39-week contract £247.80

-£263.90p/wk Catered No Availability Contract cost:Rosebery Wing: £9,996.00Myddelton Wing: £9,628.80 to £10,254.40 Contract lenght: 39 weeksSize approx: 10.5m² to 11m² Room with single bed, wash basin, wardrobe, desk and chair, lamp and storage. Duvet and pillows provided.Also see:What we provide in each hall[PDF]Table of bed sizes[PDF]Contract lengths and dates Shared bathroom 39-week contract £168.70p/wk Catered No Availability Contract cost: £6,555.20Contract lenght: 39 weeks Size approx: 15.5m² to 17.5m² Room with two single beds and a wash basin. A wardrobe, bedside table, desk and chair, lamp and storage are provided per person. Duvet and pillows provided.Also see:What we provide in each hall[PDF]Table of bed sizes[PDF]Contract lengths and dates Private bathroom 39-week contract £185.50p/wk Catered Limited Availability Contract cost: £7,208.00Contract length: 39 weeks Size approx: 17.5m² Room with two single beds and a private bathroom with shower, sink and toilet. A wardrobe, bedside table, desk and chair, lamp and storage are provided per person. Duvet and pillows provided.Also see:What we provide in each hall[PDF]Table of bed sizes[PDF]Contract lengths and dates
------

In [85]:
from bs4 import BeautifulSoup
import requests


url = "https://www.lse.ac.uk/student-life/accommodation/halls/rosebery-hall"


all_rooms_content = ""

try:
    response = requests.get(url)
    response.raise_for_status()  
    soup = BeautifulSoup(response.text, 'html.parser')
    

    rooms_divs = soup.find_all('div', class_='rooms')
    for div in rooms_divs:
        room_content = ""
        room_content += "H2: " + " ".join(h2.get_text(strip=True) for h2 in div.find_all('h2'))
        room_content += " P: " + " ".join(p.get_text(strip=True) for p in div.find_all('p'))
        all_rooms_content += room_content
    
except Exception as e:
    print("An error occurred:", e)

print(all_rooms_content)

H2: Single room Twin room Twin en suite room P: Shared bathroom 39-week contract £247.80

-£263.90p/wk Catered No Availability Contract cost:Rosebery Wing: £9,996.00Myddelton Wing: £9,628.80 to £10,254.40 Contract lenght: 39 weeksSize approx: 10.5m² to 11m² Room with single bed, wash basin, wardrobe, desk and chair, lamp and storage. Duvet and pillows provided.Also see:What we provide in each hall[PDF]Table of bed sizes[PDF]Contract lengths and dates Shared bathroom 39-week contract £168.70p/wk Catered No Availability Contract cost: £6,555.20Contract lenght: 39 weeks Size approx: 15.5m² to 17.5m² Room with two single beds and a wash basin. A wardrobe, bedside table, desk and chair, lamp and storage are provided per person. Duvet and pillows provided.Also see:What we provide in each hall[PDF]Table of bed sizes[PDF]Contract lengths and dates Private bathroom 39-week contract £185.50p/wk Catered Limited Availability Contract cost: £7,208.00Contract length: 39 weeks Size approx: 17.5m² Room with two single beds and a private bathroom with shower, sink and toilet. A wardrobe, bedside table, desk and chair, lamp and storage are provided per person. Duvet and pillows provided.Also see:What we provide in each hall[PDF]Table of bed sizes[PDF]Contract lengths and dates

In [31]:
import pandas as pd
import re



pattern = r" (Shared|Private) bathroom"
room_sections = re.split(pattern, all_rooms_content)[1:]


room_sections = [f"{room_sections[i]} bathroom{room_sections[i + 1]}" for i in range(0, len(room_sections), 2)]


room_data = []


for room in room_sections:
    room_type_search = re.search(r"(Single room|Twin room|Twin en suite room)", room)
    contract_length = re.search(r"(\d+-week contract)", room)
    price_per_week = re.search(r"£[\d.,]+( - £[\d.,]+)?p/wk", room)
    catered = "Yes" if "Catered" in room else "No"
    availability = re.search(r"(No Availability|Limited Availability)", room)
    size = re.search(r"Size approx: ([\d.]+m²( to [\d.]+m²)?)", room)

    room_info = {
        "Room Type": room_type_search.group(0) if room_type_search else "Not specified",
        "Contract Length": contract_length.group(0) if contract_length else "Not specified",
        "Price Per Week": price_per_week.group(0) if price_per_week else "Not specified",
        "Catered": catered,
        "Availability": availability.group(0) if availability else "Not specified",
        "Size": size.group(0) if size else "Not specified"
    }
    room_data.append(room_info)


df_rooms = pd.DataFrame(room_data)
df_rooms

,Room Type,Contract Length,Price Per Week,Catered,Availability,Size
0,Not specified,39-week contract,£263.90p/wk,Yes,No Availability,Size approx: 10.5m² to 11m²
1,Not specified,39-week contract,£168.70p/wk,Yes,No Availability,Size approx: 15.5m² to 17.5m²
2,Not specified,39-week contract,£185.50p/wk,Yes,Limited Availability,Size approx: 17.5m²